name: Company X Secrets Finder Service

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!master"
  
env:
  REPOSITORY_NAME: ${{ github.event.repository.name }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Echo
        run: |
          ls
      - name: Secrets Finder Action
        uses: ryuuft/test-action@v0.2.3



